{
    'name': 'Nexora App',
    'version': '19.0.1.0.0',
    'summary': 'Furniture manufacturing, customization and sales',
    'category': 'Manufacturing',
    'author': 'Mahdi',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/purchase_request_security.xml',
        'data/sequences.xml',
        'security/ir.model.access.csv',
        'data/stock_data.xml',
        'data/uom_data.xml',
        'data/job_data.xml',
        'views/product_category_views.xml',
        'views/product_type_views.xml',
        'views/material_views.xml',
        'views/printing_type_views.xml',
        'views/printing_option_views.xml',
        'views/product_views.xml',
        'views/customer_type_views.xml',
        'views/customer_views.xml',
        'views/vendor_category_views.xml',
        'views/vendor_views.xml',
        'views/sale_order_views.xml',
        'views/purchase_order_views.xml',
        'views/warehouse_views.xml',
        'views/location_views.xml',
        'views/stock_move_views.xml',
        'views/stock_product_views.xml',
        'views/bom_views.xml',
        'views/manufacturing_views.xml',
        'views/employee_views.xml',
        'views/department_views.xml',
        'reports/sale_order_report.xml',
        'reports/purchase_order_report.xml',
        'reports/manufacturing_order_report.xml',
        'reports/stock_report.xml',
        'wizard/stock_report_wizard_views.xml',
        'views/customer_partner_views.xml',
        'data/mail_template.xml',
        'data/cron.xml',
        'views/line_views.xml',
        'views/warehouse_search_views.xml',
        'views/dashboard_sales_views.xml',
        'views/dashboard_stock_views.xml',
        'views/purchase_request_views.xml',
        'views/inventory_adjustment_views.xml',
        'views/uom_views.xml',
        'views/design_views.xml',
        'views/variant_views.xml',
        'views/job_views.xml',
        'views/phase22_inherit_views.xml',
        'views/settings_views.xml',
        'views/config_views.xml',
        'views/nexora_menus.xml',
    ],
    'demo': [
        'data/demo.xml',
    ],
    'installable': True,
    'application': True,
}
