from . import product_category
from . import product_type
from . import material
from . import printing_type
from . import printing_option
from . import customer_type
from . import customer
from . import vendor_category
from . import vendor
from . import warehouse
from . import location
from . import stock_move
from . import product
from . import sale_order
from . import sale_order_line
from . import purchase_order
from . import purchase_order_line
from . import bom
from . import bom_line
from . import production_line
from . import manufacturing_order
from . import employee
from . import department
from . import customer_partner
from . import res_partner
